
version: '3'
services:
  frontend:
    image: {{ frontend_image }}
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: {{ backend_image }}
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI={{ lookup('env', 'MONGO_URI') }}
      - SESSION_SECRET={{ lookup('env', 'SESSION_SECRET') }}